name: labels_map_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  image: ^4.5.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
